### ISSUE TITLE
Stars count is not getting updated

### ISSUE THREAD

**Issue by svenanders** [vaffel/react-components#24]
Not a big issue for me, but I thought I'd mention it anyway cause you ideally want the stars to be counted correctly. Search for react-breadcrumbs and you'll see 0 stars, while in reality it has 9.

**Comment by radubrehar** [comment]
This is an issue for growing components :) which, since launch, have gained traction.

**Comment by svenanders** [comment]
Well, I agree, but since this has been an open issue for months, I don't think it'll be fixed in a jiffy

**Comment by rexxars** [comment]
I'm sorry, we're really busy with other projects lately and it pains us to leave React-Components in the state it is now. I've added some debugging info but have not yet found the culprit. The numbers are at least updates as of now, and I'll try to see if I can find out what's causing the numbers not to be updated.

**Comment by Tiagojdferreira** [comment]
@rexxars I have started looking into issue #30 which I believe is a copy of this one. Right now I am missing the key and secret for github in order to continue my debugging process. Is there any way I can contact you or @kbrabrand so you could give me the informations needed for OAuth ?

**Comment by rexxars** [comment]
You'll have to make your own, unfortunately - the number of requests per OAuth app is fairly limited. Good news is that it's fairly trivial to get one. Just go to https://github.com/settings/developers and create a new application and you should be set.

Thanks for looking into this!
