### ISSUE TITLE
Search input is blocked while results load

### ISSUE THREAD

**Issue by vith** [vaffel/react-components#29]
When typing into the search field, new characters sometimes get lost. This is easiest to reproduce when every partial length of input has results. For example, ['r', 're', 'rea', 'reac', 'react'] all have results so it's difficult to type 'react' without ending up with something like 'rt' instead.

This is happening on Chrome 43 on Arch Linux, didn't test any other environments.

**Comment by benjaminma** [comment]
It might help to debounce or throttle the SearchInput's onChange to 250 or 500ms.
