### ISSUE TITLE
Is the site down?

### ISSUE THREAD

**Issue by Tiagojdferreira** [vaffel/react-components#31]
It seems your website is down.

**Comment by kbrabrand** [comment]
Up again now. Wish we had a good explanation other than too little time. Sorry.

**Comment by Tiagojdferreira** [comment]
I am trying to run your project locally so I can contribute, but I don't seem to understand how the whole installation and deployment of the project works. I have done an npm install and I have tried running the webpack-dev-server, but it seems I am missing some compilation step that would allow me to turn the jsx into html. What is the current workflow regarding both serving the front and back end ?

**Comment by kbrabrand** [comment]
I checked just now, and to get it up and running locally this should be it:

1. Install redis
2. Clone repo
3. `npm install`

Now the app should be ready to be run. While developing `gulp watch` is probably what you want. With regards to how to run in in production we haven't had/taken the time to set it up properly. Right now we're just doing `forever node index.js`.

Sorry that this is not documentet somewhere.. But hope that this helps a bit :smile:

**Comment by Tiagojdferreira** [comment]
I am getting 

```
Segmentation fault 11
```

It seems it could be due to hiredis. I have tried reinstalling it, but I am getting an error (I think it is due to my version of node). What version of node are you using ?

**Comment by Tiagojdferreira** [comment]
It seems my problem is a conflict with my xcode and the fact that I was using gcc from macports. Now I am able to install the project, using node (v0.12.7).
However, when I run gulp watch I get the following:
```
[15:08:52] Using gulpfile ~/Documents/projects/react-components/gulpfile.js
[15:08:52] Starting 'serve'...
[15:08:53] Finished 'serve' after 659 ms
[15:08:53] Starting 'webpack:build-dev'...
Server running at: http://Tiago-MacBook-Pro.local:3000
error: Failed to fetch modules from DB: No modules returned
```
Any ideia what might be the problem ?

**Comment by kbrabrand** [comment]
That is probably because you don't have any modules in you DB. Running the module import script will probably fix it. Pointers @rexxars?

**Comment by Tiagojdferreira** [comment]
And what script would that be?

**Comment by rexxars** [comment]
`node cron/fetch-components.js`. I'll try to make a setup guide in the README today or tomorrow.

**Comment by rexxars** [comment]
I know that a lot of the dependencies we are using are pretty old. Might cause some problems on Node 4 etc. I'll look into that aswell.

**Comment by Tiagojdferreira** [comment]
@rexxars I have been documenting what I have done so far, so I can do that as my first contribution to the project if you want me to.
