### ISSUE TITLE
Remove project

### ISSUE THREAD

**Issue by demiurga** [vaffel/react-components#36]
I removed some of my project many days ago because it should not public. But the project's README page still on react-components.com. How can I remove them? or can you help me to do that please?

**Comment by rexxars** [comment]
Which project are we talking about? Can you check if it's gone now?

**Comment by apolkingg8** [comment]
Sorry I forgot the link. Seams they're still there:
http://react-components.com/component/react-native-touchable-ripple
http://react-components.com/component/react-native-swipeable-modal

**Comment by rexxars** [comment]
They should be gone now.

**Comment by apolkingg8** [comment]
Thanks a lot! :beer:
